### PR TITLE
Simplify and fix Linux install script

### PR DESCRIPTION
**Pull request by FancyChaos**
Currently the install script for Linux and MAC (install.sh) is broken and will not work on Linux systems.
The reason is the heavy usage of **bash** features which conflicts with the **sh** interpreter, which is used by the script and also recommended for universal install scripts like this one.

Keywords used in the script like *function* or *disown* are not available in pure *sh* and are a *bash* feature.

I took the radical approach and removed everything that was not needed to actually install Nord-Spotify. Due to that the used bash keyword were also removed in the process. Now the scripts works like it should with *sh*.

The "progression" bar (which just printed dots inside the terminal) is not needed at all in my opinion because the download of the necessary files only takes a second. So that should not be too much of a loss. Running the **curl** calls in parallel is also not needed due to the previously stated rather small size of files to download.

How it worked before on Linux (Using the install command from the README):

-> curl -fsSL https://raw.githubusercontent.com/Tetrax-10/Nord-Spotify/master/install-scripts/install.sh | sh
sh: 5: function: not found

How it works with the changes done in this PR:

-> curl -fsSL https://raw.githubusercontent.com/FancyChaos/Nord-Spotify/fix_linux_install/install-scripts/install.sh | sh
Downloading Nord-Spotify...
Applying theme...
warning Config "extensions" unchanged: nord.js is not on the list.
success Config changed: current_theme = Nord-Spotify
info Run "spicetify apply" to apply new config
success Config changed: color_scheme = Spotify
info Run "spicetify apply" to apply new config
success Config changed: extensions = injectNord.js
info Run "spicetify apply" to apply new config
success Config changed: inject_css = 1
info Run "spicetify apply" to apply new config
success Config changed: replace_colors = 1
info Run "spicetify apply" to apply new config
success Config changed: overwrite_assets = 1
info Run "spicetify apply" to apply new config
spicetify v2.16.2
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
OK
Transferring extensions:
OK
Transferring custom apps:
OK
success Spotify is spiced up!
All done!

### CODE REVIEW

**Comment by Tetrax-10** [comment]
Thx for the Fix. I dont have a Linux system to test but your script look good to me. Does `uninstall.sh` works properly?

**Comment by FancyChaos** [comment]
> Thx for the Fix. I dont have a Linux system to test but your script look good to me. Does `uninstall.sh` works properly?

The `uninstall.sh` script works like a charm. No issues with that.

**Comment by Tetrax-10** [comment]
Thx for the Fix @FancyChaos

**Comment by FancyChaos** [comment]
No Problem. Thank you very much for merging the changes so quickly @Tetrax-10

**Comment by Tetrax-10** [comment]
For [Windows PowerShell install script](https://github.com/Tetrax-10/Nord-Spotify/blob/master/install-scripts/install.ps1) there are two options : Auto Update Version and Offline Version.

image

If you have time can you implement that in `.sh` files? Its totally fine to ignore this request if you dont want to do it. I just asked it as I dont know shell scripting.

**Comment by FancyChaos** [comment]
> For [Windows PowerShell install script](https://github.com/Tetrax-10/Nord-Spotify/blob/master/install-scripts/install.ps1) there are two options : Auto Update Version and Offline Version.
> 
> image
> 
> If you have time can you implement that in `.sh` files? Its totally fine to ignore this request if you dont want to do it. I just asked it as I dont know shell scripting.

Can do. Should not be much of  a problem :)
Expect my PR regarding this topic in a couple of days (maybe even today).

**Pull request merged**
